In [ ]:
import numpy as np

ipynb means **Interactive Python Notebook**



In [ ]:
arr = np.array([10,20,30,40,50])
arr = np.array([10,20,30.5,40,50])
arr

array([10. , 20. , 30.5, 40. , 50. ])

**Data Type Conversion Priority(from low to high)**

bool <
int <
float <
complex <
str <
object(set, dict)

In [ ]:
# 1. bool < int

import numpy as np

a = np.array([True, False, True])
b = np.array([1, 2, 3])

result = a + b
print(result)
print(result.dtype)

[2 2 4]
int64


In [ ]:
# 2. int < float

a = np.array([1, 2, 3])
b = np.array([2.5, 3.5, 4.5])

result = a + b
print(result)
print(result.dtype)


[3.5 5.5 7.5]
float64


In [ ]:
# 3. float < complex

a = np.array([1.5, 2.5])
b = np.array([1+2j, 3+4j])

result = a + b
print(result)
print(result.dtype)


[2.5+2.j 5.5+4.j]
complex128


In [ ]:
# 4. Mixing All Numeric Types

a = np.array([True, 5, 2.5])
print(a)
print(a.dtype)


[1.  5.  2.5]
float64


In [ ]:
# typeError

a = np.array([1, 2, 3])
b = np.array(["a", "b", "c"])

result = a + b


In [ ]:
a = np.array([1, 2, 3, "4"])
print(a.dtype)

'''Explanation:

NumPy converts everything to string type.

<U21 means Unicode string.'''

<U21


In [ ]:
a = np.array([1, 2.5, "hello", [1,2]])
print(a.dtype)

# ValueError because of dimensionality, same will happen with tuple too

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (4,) + inhomogeneous part.

In [ ]:
a = np.array([1, 2.5, "hello", {1,2}])
print(a.dtype)

object


**Types of Arrays:**

1. 1D Array
2. 2D Array
3. Multi dimensional Array

In [ ]:

arr_1d = np.array([1, 2, 3, 4, 5])
print(arr_1d)

[1 2 3 4 5]


In [ ]:

arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
print(arr_2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:

arr_3d = np.array([[[1, 2, 3],
                    [4, 5, 6]],

                   [[7, 8, 9],
                    [10, 11, 12]]])
print(arr_3d)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


# **Key functions of numpy:**



1.   *np.__version__* : It is an inbuilt attribute which is used to check the version of the library



```
print("NumPy Version:", np.__version__)
```
---

2.   *np.array()* : It is an inbuilt method which is used to create an array



```
arr = np.array([1, 2, 3, 4, 5])
print("Array:", arr)
```
---

3.   *arr.ndim* : It is an inbuilt attribute used to find the type of dimension



```
print("Number of Dimensions:", arr.ndim)
```
---

4.   *arr.dtype* : It is an inbuilt attribute used to find the datatype of the array



```
print("Datatype of arr:", arr.dtype)
```
---

5.   *np.arange(start,end+-1, step)* : It is an inbuilt method which is used to create a uni-dimensional array within specified limits



```
a = np.arange(1, 10, 2)   # from 1 to 9, step 2
print("Arange Array:", a)
```
---

6.  *arr.shape* : It is an inbuilt attribute which will return the number of rows and columns. It returns a tuple. If the array is a 1D array, it return the number of values in the format (val, ). Incase of 2D array, it returns in the form of (r,c). Incase of Multi-dimensional array it returns in the form (r,c,v).



```
arr = np.array([1,2,3])
arr.shape
```
---
7.  *arr.reshape(r,c)* : It is an inbuilt method used to convert from one dimension to another dimension. **rule** : the product of the row and column should be equal to the total values in the array. If we pass '-1' as an arguement for reshape method, it flattens the array, it converts the array into a 1D array.



```
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9],
                   [10,11,12])

arr_2d.reshape(6,2)
arr_2d.reshape(-1)
```
---
8.  *np.linspace(start, end, n)* : It will generate an array of length 'n' with equally spaced values. By default 50 values are generated.



```
np.linspace(1,5,10)
```
---
9. *np.zeros()* : It creates an array filled with only zeros.

    **Syntax**:  np.zeros(n) --> 1D | np.zeros((r,c)) --> 2D | np.zeros((r,c,v)) --> 3D




```
np.zeros((2,5))
```
---
10. *np.ones()* : It creates an array filled with only ones. Has same syntax as above method.

```
np.ones(10)
```
---
11. *np.identity(n)* : It creates an identity matrix of size N x N.

```
np.identity(5)
```
---
12. *np.random.randint(start, end, n)* : It is used to generate int data randomly of size n. If size n is not passed, it returns just 1 value.

```
np.random.randint(start, end, n)
```
---
13. *np.random.rand(n)*: It always generated values between 0 to 1 of size n. By default it generated only 1 value.

```
np.random.rand(10)
```
---
14. *np.random.randn(n)*: It always creates random values from -infinite to +infinite of size n. the n in randn stands for negative.

```
np.random.randn(0)
```
---

In [ ]:
arr_1d = np.array([1, 2, 3, 4, 5])
print(arr_1d)

arr_1d.shape

[1 2 3 4 5]


(5,)

In [ ]:

arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
print(arr_2d)

arr_2d.shape

[[1 2 3]
 [4 5 6]
 [7 8 9]]


(3, 3)

In [ ]:

arr_3d = np.array([[[1, 2, 3],
                    [4, 5, 6]],

                   [[7, 8, 9],
                    [10, 11, 12]]])
print(arr_3d)
arr_3d.shape

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


(2, 2, 3)

In [ ]:
al = np.linspace(1,5,10)
al

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [ ]:
np.zeros((2,5,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [ ]:
np.random.randint(1,10)
rand = np.random.randint(1,45,10)
rand

array([ 8,  7, 26, 16, 32, 32, 38, 29,  9, 20])

In [ ]:
np.random.rand(10)

array([0.07546962, 0.20350535, 0.25073333, 0.54682607, 0.83833297,
       0.21348353, 0.01928187, 0.42434772, 0.76894318, 0.46030153])

In [ ]:
np.random.randn(25)

array([ 1.05045449, -0.95162758, -0.68658601,  0.02713323,  1.72464885,
        1.55439162,  1.20938338, -0.01639328, -1.52351352,  0.07671348,
       -0.05062984, -0.16277888,  1.21195277,  0.10625341,  1.15670559,
       -0.62113185, -0.567552  ,  0.9440898 , -0.63050755, -0.30990248,
       -0.11599263,  0.87131522, -0.20461608,  1.70884276, -1.87545759])

# **Indexing and slicing on arrays**

***Indexing*** : It is the process of fetching a single elements from an array

Syntax:

1. 1D --> arr[index]
2. 2D --> arr[row_index, col_index]
3. 3D --> [row_index, col_index, val_index]



---
***Slicing*** : It is the process of fetching more than one element from an array.

Syntax:

1. 1D --> arr[start : end : step]
2. 2D --> arr[row_slice, col_slice]
3. 3D --> arr[row_slice, col_slice : val_slice]


In [ ]:
idx = np.array([[1,2,3,4],
                [4,5,6,5],
                [7,8,9,5]])
idx[2,0]
idx[0:1, :]
idx[0:2, 0:2]
idx[::2, :2]
idx[:, 1::2]

array([[2, 4],
       [5, 5],
       [8, 5]])

In [ ]:
idx = np.array([[[1,2,3,4],
                 [5,6,7,8]],

                [[9,10,11,12],
                 [13,14,15,16]]])

idx[0,1,0]
idx[0:1, 1:, :]
idx[0:1, :, :3]

array([[[1, 2, 3],
        [5, 6, 7]]])

#**Operations on Arrays**

On Arrays in numpy, we can perform operations in three ways:

1. Array with array
2. Array with constant/scalar
3. Math operations using inbuilt methods

---

**1. Array with array** : It performs element wise operation. It is also called as **vectorization**.

arr1 (operator) arr2

Arithmetic Operators: +, -, *, /, //, **, %

Bitwise Operators: &, |, ^, <<, >>, ~

Logical Operators: error is thrown due to ambiguity, use any() or all()


*Rules* :


*   We need minimum two arrays.
*   Both arrays should be of the same length.

---

**2. Array with constant/scalar** : It performs element wise operation.

* arr (operator) constant
* constant (operator) arr

Arithmetic Operators: +, -, *, /, //, **, %

Bitwise Operators: &, |, ^, <<, >>

Logical Operators: error is thrown due to ambiguity, use any() or all()

---

**3. Math operations using inbuilt methods** : It performs group wise operation.

Some popular operations are sum, mean, size, min, max, sqrt, log, exp, cos, subtract

---


In [ ]:
arr1 = np.arange(1,7)
arr2 = np.arange(4,10)

print(arr1)
print(arr2)

arr1 + arr2
arr1 - arr2
arr1 * arr2
arr1 << arr2

[1 2 3 4 5 6]
[4 5 6 7 8 9]


array([  16,   64,  192,  512, 1280, 3072])

In [ ]:
arr1 = np.array([[1,2,3],
                 [4,5,6]])

arr2 = np.array([[1,2,3],
                 [4,5,6]])

arr1 + arr2
arr1 & arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
# if a 1D array and multi-dimensional array is taken. Then the 1D array is added to all the columns in the ND array

arr1 = np.array([[0,2,3],
                 [4,5,6]])

arr2 = np.array([1,2,3])

arr1 + arr2
~arr2

array([-2, -3, -4])

In [ ]:
# In Python, all Default values are considered False and rest of the values(non default values) are considered as True.
arr1.all() and arr2.all()
arr1.any() and arr2.any()

np.True_

In [ ]:
arr = np.arange(1,6)
print(arr)
arr + 2
2 + arr
arr * 2.5
arr / 5
arr << 1

[1 2 3 4 5]


array([ 2,  4,  6,  8, 10])

In [ ]:
np.sum(arr)
np.mean(arr)
arr.size
np.log(arr)
np.exp(arr)

array([  2.71828183,   7.3890561 ,  20.08553692,  54.59815003,
       148.4131591 ])

# **Broadcasting**

Even though the dimensions of the arrays are different, vectorization will happen.

*Note* : numpy checks the shape from right to left.

*Rule* : Two dimensions are compatible if
1. They are equal (or)
2. One of them is 1

Think of broadcasting as:

* Expanding rows

* Expanding columns

* Without copying actual data

* Only logical expansion

In [ ]:
arr1 = np.array([[1,2,3],
                 [4,5,6]])

arr2 = np.array([1,2,3,4])

print("arr1: ", arr1.shape)
print("arr2: ", arr2.shape)


arr1:  (2, 3)
arr2:  (4,)


In [ ]:
a = np.array([[1,2,3],
              [4,5,6]])

b = np.array([[10],
              [20]])

print(a + b)


[[11 12 13]
 [24 25 26]]


# Task questions


In [ ]:
arr1 = np.linspace(0,51,10)
print("1D array of 10 equally spaced values between 0 to 50: \n", arr1)

1D array of 10 equally spaced values between 0 to 50: 
 [ 0.          5.66666667 11.33333333 17.         22.66666667 28.33333333
 34.         39.66666667 45.33333333 51.        ]


In [ ]:
arr2 = np.random.randint(5,21,9)
arr2
arr2 = arr1.reshape(3,3)
arr2

array([[16, 15,  9],
       [ 5,  8, 20],
       [ 6,  8, 16]])

In [ ]:
print(arr1.shape)
print(arr2.shape)

print(arr1.ndim)
print(arr2.ndim)

(10,)
(3, 3)
1
2


In [ ]:
arr1 = arr1.reshape(2,5)
print(arr1)
print("shape  after reshaping: ", arr1.shape)
arr1 = arr1.reshape(-1)
print(arr1)
print("shape after flattening: ", arr1.shape)

[[ 0.          5.66666667 11.33333333 17.         22.66666667]
 [28.33333333 34.         39.66666667 45.33333333 51.        ]]
shape  after reshaping:  (2, 5)
[ 0.          5.66666667 11.33333333 17.         22.66666667 28.33333333
 34.         39.66666667 45.33333333 51.        ]
shape after flattening:  (10,)


In [ ]:
print(arr2[1,2])
print(arr2[0])
print(arr2[1])
print(arr1[:5])
print(arr1[::-1])
print(arr2[:, 1:])

20
[16 15  9]
[ 5  8 20]
[ 0.          5.66666667 11.33333333 17.         22.66666667]
[51.         45.33333333 39.66666667 34.         28.33333333 22.66666667
 17.         11.33333333  5.66666667  0.        ]
[[15  9]
 [ 8 20]
 [ 8 16]]


In [ ]:
arr3 = np.arange(1,11)
print(arr1 + arr3)

print(arr1 * arr3)

print(arr3 - 5)

[ 1.          7.66666667 14.33333333 21.         27.66666667 34.33333333
 41.         47.66666667 54.33333333 61.        ]
[  0.          11.33333333  34.          68.         113.33333333
 170.         238.         317.33333333 408.         510.        ]
[-4 -3 -2 -1  0  1  2  3  4  5]


In [ ]:
arr4 = np.random.rand(5)
print(arr4)

arr5 = np.random.randint(-1,2,5)
print(arr5)

[0.63389714 0.31040364 0.38721797 0.00483946 0.30355684]
[-1  0  1  0 -1]


In [ ]:
n = int(input("Enter a number: "))
arr = np.random.randint(1,100,n*n)
arr = arr.reshape(n,n)
print(arr)


Enter a number: 7
[[52 19 87 48 63 35 86]
 [ 6 30  8  3 23 45 84]
 [80  1 66 30 60 76  9]
 [98 45 28 67 65 52 77]
 [84 32 77 41 63 56 61]
 [93 60 16 33 35 29 91]
 [91 44 27 86 55 16 19]]


In [ ]:
print(np.sum(arr))

2452
